version: '3'
services:
  splunk:
    build: ./splunk 
    image: simdata-splunk
    ports:
      - 8000:8000
      - 8088:8088
      - 8089:8089
    environment:
      SPLUNK_START_ARGS: "--accept-license --answer-yes  --seed-passwd changeme"
      SPLUNK_USER: "root"
  simdata:
    depends_on:
      - "splunk"
    ports:
      - 11013:11013
    build: .
    image: simdata